// PART 1 - Andhra Pradesh & Assam Colleges
const AP_COLLEGES = [
  // Engineering AP
  { name: "Andhra University College of Engineering", location: "Visakhapatnam, Andhra Pradesh", state: "Andhra Pradesh", department: "engineering", type: "Government", gender: "Co-Education", rating: 4.4, minPercentage: 80, annualFee: "45000", placementRate: 82, topCompanies: ["TCS", "Infosys", "Wipro", "HCL", "Tech Mahindra", "Cognizant"], hostelAvailable: true, naacGrade: "A", established: 1935, description: "One of the oldest and most prestigious engineering colleges in AP.", courses: ["B.Tech CSE", "B.Tech ECE", "B.Tech Mech", "B.Tech Civil", "B.Tech Chemical"], highlight: "Oldest engineering college in AP", mapQuery: "Andhra University College of Engineering Visakhapatnam" },
  { name: "JNTU Anantapur", location: "Anantapur, Andhra Pradesh", state: "Andhra Pradesh", department: "engineering", type: "Government", gender: "Co-Education", rating: 4.2, minPercentage: 72, annualFee: "35000", placementRate: 78, topCompanies: ["TCS", "Infosys", "Wipro", "HCL", "Tech Mahindra"], hostelAvailable: true, naacGrade: "A", established: 1981, description: "Jawaharlal Nehru Technological University campus in Anantapur.", courses: ["B.Tech CSE", "B.Tech ECE", "B.Tech Mech", "B.Tech Civil"], highlight: "Top government university in Rayalaseema", mapQuery: "JNTU Anantapur Andhra Pradesh" },
  { name: "KL University", location: "Vijayawada, Andhra Pradesh", state: "Andhra Pradesh", department: "engineering", type: "Private", gender: "Co-Education", rating: 4.3, minPercentage: 70, annualFee: "150000", placementRate: 83, topCompanies: ["TCS", "Infosys", "Wipro", "Amazon", "Microsoft", "Cognizant"], hostelAvailable: true, naacGrade: "A+", established: 1980, description: "Deemed university with strong industry partnerships and research.", courses: ["B.Tech CSE", "B.Tech ECE", "B.Tech Mech", "B.Tech AI&ML", "B.Tech IT"], highlight: "Top private university in AP", mapQuery: "KL University Vijayawada Andhra Pradesh" },
  { name: "GITAM University", location: "Visakhapatnam, Andhra Pradesh", state: "Andhra Pradesh", department: "engineering", type: "Private", gender: "Co-Education", rating: 4.2, minPercentage: 68, annualFee: "160000", placementRate: 80, topCompanies: ["TCS", "Infosys", "Wipro", "IBM", "Capgemini"], hostelAvailable: true, naacGrade: "A", established: 1980, description: "Multi-campus university offering quality technical education.", courses: ["B.Tech CSE", "B.Tech ECE", "B.Tech Mech", "B.Tech Civil", "B.Tech EEE"], highlight: "Strong research and innovation culture", mapQuery: "GITAM University Visakhapatnam Andhra Pradesh" },
  { name: "VIT-AP University", location: "Amaravati, Andhra Pradesh", state: "Andhra Pradesh", department: "engineering", type: "Private", gender: "Co-Education", rating: 4.1, minPercentage: 65, annualFee: "180000", placementRate: 79, topCompanies: ["TCS", "Infosys", "Wipro", "Zoho", "Cognizant"], hostelAvailable: true, naacGrade: "A", established: 2017, description: "New campus of VIT Group with modern infrastructure.", courses: ["B.Tech CSE", "B.Tech ECE", "B.Tech Mech", "B.Tech AI&ML"], highlight: "VIT brand quality in AP", mapQuery: "VIT-AP University Amaravati Andhra Pradesh" },
  { name: "Vignan University", location: "Guntur, Andhra Pradesh", state: "Andhra Pradesh", department: "engineering", type: "Private", gender: "Co-Education", rating: 4.0, minPercentage: 65, annualFee: "120000", placementRate: 76, topCompanies: ["TCS", "Infosys", "Wipro", "HCL", "Tech Mahindra"], hostelAvailable: true, naacGrade: "A", established: 2008, description: "Deemed university with focus on technical and management education.", courses: ["B.Tech CSE", "B.Tech ECE", "B.Tech Mech", "B.Tech Civil"], highlight: "Strong industrial collaborations", mapQuery: "Vignan University Guntur Andhra Pradesh" },
  { name: "SRM University AP", location: "Amaravati, Andhra Pradesh", state: "Andhra Pradesh", department: "engineering", type: "Private", gender: "Co-Education", rating: 4.1, minPercentage: 65, annualFee: "175000", placementRate: 78, topCompanies: ["TCS", "Infosys", "Wipro", "Amazon", "Samsung"], hostelAvailable: true, naacGrade: "A", established: 2017, description: "SRM Group campus in the new capital region of AP.", courses: ["B.Tech CSE", "B.Tech ECE", "B.Tech Mech", "B.Tech IT"], highlight: "SRM brand with modern campus", mapQuery: "SRM University AP Amaravati Andhra Pradesh" },
  // Medical AP
  { name: "Andhra Medical College", location: "Visakhapatnam, Andhra Pradesh", state: "Andhra Pradesh", department: "medical", type: "Government", gender: "Co-Education", rating: 4.6, minPercentage: 90, annualFee: "18000", placementRate: 95, topCompanies: ["King George Hospital", "Apollo Hospitals", "Fortis", "Government Hospitals", "Care Hospitals"], hostelAvailable: true, naacGrade: "A+", established: 1923, description: "One of the oldest and most prestigious medical colleges in AP.", courses: ["MBBS", "BDS", "Nursing", "B.Pharm"], highlight: "Oldest medical college in AP", mapQuery: "Andhra Medical College Visakhapatnam Andhra Pradesh" },
  { name: "Guntur Medical College", location: "Guntur, Andhra Pradesh", state: "Andhra Pradesh", department: "medical", type: "Government", gender: "Co-Education", rating: 4.4, minPercentage: 87, annualFee: "15000", placementRate: 93, topCompanies: ["GGH Guntur", "Apollo", "KIMS", "Government Hospitals", "Narayana Health"], hostelAvailable: true, naacGrade: "A", established: 1946, description: "Government medical college with excellent clinical training facilities.", courses: ["MBBS", "BDS", "Nursing"], highlight: "Strong clinical training in Guntur", mapQuery: "Guntur Medical College Andhra Pradesh" },
  { name: "NRI Medical College", location: "Guntur, Andhra Pradesh", state: "Andhra Pradesh", department: "medical", type: "Private", gender: "Co-Education", rating: 4.2, minPercentage: 82, annualFee: "750000", placementRate: 90, topCompanies: ["Apollo", "Fortis", "KIMS", "Narayana Health", "Care Hospitals"], hostelAvailable: true, naacGrade: "A", established: 1993, description: "Private medical college with NRI focus and modern hospital facilities.", courses: ["MBBS", "BDS", "Nursing"], highlight: "Top private medical college in AP", mapQuery: "NRI Medical College Guntur Andhra Pradesh" },
  // Arts Science AP
  { name: "Andhra University", location: "Visakhapatnam, Andhra Pradesh", state: "Andhra Pradesh", department: "arts_science", type: "Government", gender: "Co-Education", rating: 4.3, minPercentage: 65, annualFee: "20000", placementRate: 72, topCompanies: ["TCS", "Infosys", "Banks", "Government Jobs", "Teaching"], hostelAvailable: true, naacGrade: "A+", established: 1926, description: "Premier central university in AP offering diverse academic programs.", courses: ["B.Sc Physics", "B.Sc Chemistry", "B.Sc Maths", "B.A English", "B.A History", "B.Com"], highlight: "Top university in AP - 95+ years legacy", mapQuery: "Andhra University Visakhapatnam Andhra Pradesh" },
  { name: "Sri Venkateswara University", location: "Tirupati, Andhra Pradesh", state: "Andhra Pradesh", department: "arts_science", type: "Government", gender: "Co-Education", rating: 4.2, minPercentage: 60, annualFee: "18000", placementRate: 70, topCompanies: ["TCS", "Banks", "Government Jobs", "Teaching", "Infosys"], hostelAvailable: true, naacGrade: "A", established: 1954, description: "Located in the holy city of Tirupati, offering quality education.", courses: ["B.Sc Physics", "B.Sc Chemistry", "B.A English", "B.Com", "BBA"], highlight: "Located in the holy city of Tirupati", mapQuery: "Sri Venkateswara University Tirupati Andhra Pradesh" },
  // Law AP
  { name: "Damodaram Sanjivayya National Law University", location: "Visakhapatnam, Andhra Pradesh", state: "Andhra Pradesh", department: "law", type: "Government", gender: "Co-Education", rating: 4.3, minPercentage: 70, annualFee: "45000", placementRate: 80, topCompanies: ["High Court", "Law Firms", "Corporate Legal", "Government", "Advocate Practice"], hostelAvailable: true, naacGrade: "A", established: 2008, description: "National law university in AP offering quality legal education.", courses: ["LLB", "BBA LLB", "B.Com LLB", "BA LLB"], highlight: "Only National Law University in AP", mapQuery: "Damodaram Sanjivayya National Law University Visakhapatnam" },
  // Commerce AP
  { name: "Acharya Nagarjuna University", location: "Guntur, Andhra Pradesh", state: "Andhra Pradesh", department: "commerce", type: "Government", gender: "Co-Education", rating: 4.1, minPercentage: 58, annualFee: "22000", placementRate: 68, topCompanies: ["TCS", "Banks", "Government", "CA Firms", "Teaching"], hostelAvailable: true, naacGrade: "A", established: 1976, description: "Largest affiliating university in AP with strong commerce programs.", courses: ["B.Com", "BBA", "B.Sc CS", "M.Com"], highlight: "Largest affiliating university in AP", mapQuery: "Acharya Nagarjuna University Guntur Andhra Pradesh" },
  // Management AP
  { name: "IIM Visakhapatnam", location: "Visakhapatnam, Andhra Pradesh", state: "Andhra Pradesh", department: "management", type: "Government", gender: "Co-Education", rating: 4.5, minPercentage: 80, annualFee: "1800000", placementRate: 96, topCompanies: ["McKinsey", "Deloitte", "Amazon", "Microsoft", "Goldman Sachs", "BCG"], hostelAvailable: true, naacGrade: "A+", established: 2015, description: "IIM in the port city of Vizag offering world-class management education.", courses: ["MBA", "PGP", "Executive MBA"], highlight: "IIM brand in AP", mapQuery: "IIM Visakhapatnam Andhra Pradesh" },
  // Agriculture AP
  { name: "Acharya NG Ranga Agricultural University", location: "Guntur, Andhra Pradesh", state: "Andhra Pradesh", department: "agriculture", type: "Government", gender: "Co-Education", rating: 4.3, minPercentage: 65, annualFee: "25000", placementRate: 75, topCompanies: ["Monsanto", "ITC Agri", "Mahindra Agri", "ICAR", "Government Agri Dept", "Nuziveedu Seeds"], hostelAvailable: true, naacGrade: "A", established: 1964, description: "Premier agricultural university serving Andhra Pradesh farmers and researchers.", courses: ["B.Sc Agriculture", "B.Sc Horticulture", "B.Sc Forestry", "B.Tech Food Tech"], highlight: "Top agricultural university in AP", mapQuery: "Acharya NG Ranga Agricultural University Guntur AP" },
  // Pharmacy AP
  { name: "GITAM School of Pharmacy", location: "Visakhapatnam, Andhra Pradesh", state: "Andhra Pradesh", department: "pharmacy", type: "Private", gender: "Co-Education", rating: 4.1, minPercentage: 65, annualFee: "95000", placementRate: 78, topCompanies: ["Sun Pharma", "Dr Reddys", "Cipla", "Aurobindo Pharma", "Divi Labs", "Hetero Drugs"], hostelAvailable: true, naacGrade: "A", established: 2001, description: "GITAM pharmacy school with strong industry connections in pharma sector.", courses: ["B.Pharm", "Pharm.D", "M.Pharm"], highlight: "Strong AP pharma industry connections", mapQuery: "GITAM School of Pharmacy Visakhapatnam AP" },
  // Architecture AP
  { name: "Jawaharlal Nehru Architecture & Fine Arts University", location: "Hyderabad, Telangana", state: "Andhra Pradesh", department: "architecture", type: "Government", gender: "Co-Education", rating: 4.5, minPercentage: 78, annualFee: "35000", placementRate: 83, topCompanies: ["Hafeez Contractor", "CP Kukreja", "Morphogenesis", "HOK", "Gensler", "Arcop"], hostelAvailable: true, naacGrade: "A+", established: 1949, description: "Dedicated architecture university offering specialized design education.", courses: ["B.Arch", "B.Planning", "M.Arch", "Interior Design"], highlight: "Only dedicated architecture university in South India", mapQuery: "Jawaharlal Nehru Architecture Fine Arts University Hyderabad" },
  // Education AP
  { name: "Sri Venkateswara University Education", location: "Tirupati, Andhra Pradesh", state: "Andhra Pradesh", department: "education", type: "Government", gender: "Co-Education", rating: 4.0, minPercentage: 55, annualFee: "15000", placementRate: 72, topCompanies: ["Kendriya Vidyalaya", "Navodaya Vidyalaya", "State Schools", "Private Schools", "DIET"], hostelAvailable: true, naacGrade: "B+", established: 1955, description: "B.Ed program at one of AP oldest universities.", courses: ["B.Ed", "M.Ed", "D.El.Ed"], highlight: "Teacher training in holy Tirupati", mapQuery: "Sri Venkateswara University Education Department Tirupati" },
];

const ASSAM_COLLEGES = [
  { name: "IIT Guwahati", location: "Guwahati, Assam", state: "Assam", department: "engineering", type: "Government", gender: "Co-Education", rating: 4.7, minPercentage: 95, annualFee: "100000", placementRate: 91, topCompanies: ["Google", "Microsoft", "Amazon", "Flipkart", "Samsung", "Qualcomm", "TCS"], hostelAvailable: true, naacGrade: "A++", established: 1994, description: "Gateway IIT serving North-East India with excellent research facilities.", courses: ["B.Tech CSE", "B.Tech ECE", "B.Tech Mech", "B.Tech Civil", "B.Tech Chemical"], highlight: "Premier IIT for North-East India", mapQuery: "IIT Guwahati Assam" },
  { name: "NIT Silchar", location: "Silchar, Assam", state: "Assam", department: "engineering", type: "Government", gender: "Co-Education", rating: 4.4, minPercentage: 82, annualFee: "65000", placementRate: 84, topCompanies: ["TCS", "Infosys", "Wipro", "Amazon", "HCL", "Capgemini", "Cognizant"], hostelAvailable: true, naacGrade: "A", established: 1967, description: "National Institute of Technology in Assam with strong academic programs.", courses: ["B.Tech CSE", "B.Tech ECE", "B.Tech Mech", "B.Tech Civil", "B.Tech EEE"], highlight: "Top NIT in North-East India", mapQuery: "NIT Silchar Assam" },
  { name: "Tezpur University", location: "Tezpur, Assam", state: "Assam", department: "engineering", type: "Government", gender: "Co-Education", rating: 4.3, minPercentage: 78, annualFee: "55000", placementRate: 80, topCompanies: ["TCS", "Infosys", "Wipro", "HCL", "Tech Mahindra", "BSNL"], hostelAvailable: true, naacGrade: "A+", established: 1994, description: "Central university with strong research in science and technology.", courses: ["B.Tech CSE", "B.Tech ECE", "B.Tech Mech", "B.Sc Physics", "B.Sc Chemistry"], highlight: "Best central university in North-East", mapQuery: "Tezpur University Assam" },
  { name: "Assam Engineering College", location: "Guwahati, Assam", state: "Assam", department: "engineering", type: "Government", gender: "Co-Education", rating: 4.1, minPercentage: 72, annualFee: "40000", placementRate: 76, topCompanies: ["TCS", "Infosys", "Wipro", "Oil India", "ONGC", "PWD Assam"], hostelAvailable: true, naacGrade: "A", established: 1955, description: "Oldest and most prestigious engineering college in Assam.", courses: ["B.Tech CSE", "B.Tech ECE", "B.Tech Mech", "B.Tech Civil", "B.Tech EEE"], highlight: "Oldest engineering college in Assam", mapQuery: "Assam Engineering College Guwahati" },
  { name: "Gauhati Medical College", location: "Guwahati, Assam", state: "Assam", department: "medical", type: "Government", gender: "Co-Education", rating: 4.5, minPercentage: 88, annualFee: "14000", placementRate: 94, topCompanies: ["GMCH Hospital", "AIIMS", "Apollo", "Fortis", "Government Hospitals NE", "Narayana Health"], hostelAvailable: true, naacGrade: "A", established: 1960, description: "Premier government medical college in Assam with excellent clinical training.", courses: ["MBBS", "BDS", "Nursing", "Paramedical"], highlight: "Largest hospital in North-East India", mapQuery: "Gauhati Medical College Guwahati Assam" },
  { name: "Assam Medical College", location: "Dibrugarh, Assam", state: "Assam", department: "medical", type: "Government", gender: "Co-Education", rating: 4.3, minPercentage: 85, annualFee: "13000", placementRate: 92, topCompanies: ["Assam Medical College Hospital", "Government Hospitals", "Apollo", "Fortis", "Tata Cancer Research"], hostelAvailable: true, naacGrade: "A", established: 1947, description: "One of the oldest medical colleges in North-East India.", courses: ["MBBS", "BDS", "Nursing"], highlight: "Serving Upper Assam and Arunachal Pradesh", mapQuery: "Assam Medical College Dibrugarh" },
  { name: "Gauhati University", location: "Guwahati, Assam", state: "Assam", department: "arts_science", type: "Government", gender: "Co-Education", rating: 4.2, minPercentage: 60, annualFee: "12000", placementRate: 68, topCompanies: ["TCS", "Banks", "Government Jobs", "Teaching", "Research Institutes"], hostelAvailable: true, naacGrade: "A+", established: 1948, description: "Premier university in Assam offering diverse academic programs.", courses: ["B.Sc Physics", "B.Sc Chemistry", "B.Sc Maths", "B.A English", "B.A Political Science", "B.Com"], highlight: "Premier university of North-East India", mapQuery: "Gauhati University Guwahati Assam" },
  { name: "Dibrugarh University", location: "Dibrugarh, Assam", state: "Andhra Pradesh", department: "arts_science", type: "Government", gender: "Co-Education", rating: 4.1, minPercentage: 58, annualFee: "10000", placementRate: 65, topCompanies: ["Oil India", "ONGC", "Banks", "Teaching", "Government Jobs"], hostelAvailable: true, naacGrade: "A", established: 1965, description: "University serving the upper Assam and surrounding regions.", courses: ["B.Sc Physics", "B.Sc Chemistry", "B.A English", "B.Com", "B.A Assamese"], highlight: "Petroleum industry connections in Upper Assam", mapQuery: "Dibrugarh University Assam" },
  { name: "Assam Agricultural University", location: "Jorhat, Assam", state: "Assam", department: "agriculture", type: "Government", gender: "Co-Education", rating: 4.2, minPercentage: 62, annualFee: "18000", placementRate: 74, topCompanies: ["Tea Research Association", "ICAR", "Oil Palm India", "State Agri Dept", "Tata Tea", "Brooke Bond"], hostelAvailable: true, naacGrade: "A", established: 1969, description: "Premier agricultural university serving North-East India with tea and crop research.", courses: ["B.Sc Agriculture", "B.Sc Horticulture", "B.Sc Forestry", "B.V.Sc"], highlight: "World famous tea research facilities", mapQuery: "Assam Agricultural University Jorhat Assam" },
  { name: "IIM Guwahati", location: "Guwahati, Assam", state: "Assam", department: "management", type: "Government", gender: "Co-Education", rating: 4.5, minPercentage: 80, annualFee: "1900000", placementRate: 97, topCompanies: ["McKinsey", "BCG", "Amazon", "Microsoft", "Goldman Sachs", "Deloitte", "KPMG"], hostelAvailable: true, naacGrade: "A++", established: 1995, description: "IIM serving North-East India with top business education.", courses: ["MBA", "PGP", "Executive MBA"], highlight: "Gateway IIM for North-East India", mapQuery: "IIM Guwahati Assam" },
];
